services:
  db:
    image: postgres:18
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events
      POSTGRES_DB: events
    healthcheck:
      test: pg_isready -U events -d events
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/.games
